/**
 * PDF Generation Utilities
 *
 * Creates downloadable PDFs from notes, essays, and other content.
 * Uses jsPDF for client-side PDF generation.
 */

import { jsPDF } from 'jspdf';

// Types for PDF generation
interface PDFOptions {
  title: string;
  author?: string;
  subject?: string;
  orientation?: 'portrait' | 'landscape';
  format?: 'a4' | 'letter';
  margins?: { top: number; right: number; bottom: number; left: number };
}

interface ContentBlock {
  type: 'heading' | 'paragraph' | 'list' | 'quote' | 'divider';
  content: string | string[];
  level?: number; // For headings (1-6)
}

// Default options
const defaultOptions: PDFOptions = {
  title: 'UPSC PrepX-AI Document',
  author: 'UPSC PrepX-AI',
  subject: 'Study Material',
  orientation: 'portrait',
  format: 'a4',
  margins: { top: 20, right: 15, bottom: 20, left: 15 },
};

// Colors
const colors = {
  primary: [0, 243, 255] as [number, number, number], // Neon blue
  text: [30, 30, 30] as [number, number, number],
  heading: [20, 20, 40] as [number, number, number],
  muted: [100, 100, 100] as [number, number, number],
};

/**
 * Generate PDF from content blocks
 */
export async function generatePDF(
  blocks: ContentBlock[],
  options: Partial<PDFOptions> = {}
): Promise<Blob> {
  const opts = { ...defaultOptions, ...options };

  const doc = new jsPDF({
    orientation: opts.orientation,
    unit: 'mm',
    format: opts.format,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const marginLeft = opts.margins!.left;
  const marginRight = pageWidth - opts.margins!.right;
  const contentWidth = marginRight - marginLeft;

  let yPosition = opts.margins!.top;
  const lineHeight = 6; // mm

  // Title page
  doc.setFillColor(...colors.heading);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setTextColor(...colors.primary);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');

  const titleLines = doc.splitTextToSize(opts.title, contentWidth);
  doc.text(titleLines, pageWidth / 2, pageHeight / 2 - 10, { align: 'center' });

  doc.setTextColor(200, 200, 200);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by UPSC PrepX-AI`, pageWidth / 2, pageHeight / 2 + 10, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), pageWidth / 2, pageHeight / 2 + 20, { align: 'center' });

  doc.addPage();

  // Content pages
  yPosition = opts.margins!.top;

  for (const block of blocks) {
    // Check if we need a new page
    if (yPosition > pageHeight - opts.margins!.bottom - 20) {
      doc.addPage();
      yPosition = opts.margins!.top;
    }

    switch (block.type) {
      case 'heading':
        const fontSize = block.level === 1 ? 18 : block.level === 2 ? 14 : 12;
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...colors.heading);

        const headingLines = doc.splitTextToSize(
          typeof block.content === 'string' ? block.content : block.content[0],
          contentWidth
        );
        doc.text(headingLines, marginLeft, yPosition);
        yPosition += headingLines.length * lineHeight + 4;
        break;

      case 'paragraph':
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...colors.text);

        const paraLines = doc.splitTextToSize(
          typeof block.content === 'string' ? block.content : block.content.join(' '),
          contentWidth
        );
        doc.text(paraLines, marginLeft, yPosition);
        yPosition += paraLines.length * lineHeight + 3;
        break;

      case 'list':
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...colors.text);

        const items = typeof block.content === 'string' ? [block.content] : block.content;
        for (const item of items) {
          if (yPosition > pageHeight - opts.margins!.bottom - 10) {
            doc.addPage();
            yPosition = opts.margins!.top;
          }

          const bulletLines = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
          doc.text(bulletLines, marginLeft + 3, yPosition);
          yPosition += bulletLines.length * lineHeight;
        }
        yPosition += 2;
        break;

      case 'quote':
        doc.setFontSize(11);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...colors.muted);

        const quoteText = typeof block.content === 'string' ? block.content : block.content[0];
        const quoteLines = doc.splitTextToSize(`"${quoteText}"`, contentWidth - 10);
        doc.text(quoteLines, marginLeft + 5, yPosition);
        yPosition += quoteLines.length * lineHeight + 5;
        break;

      case 'divider':
        doc.setDrawColor(...colors.primary);
        doc.setLineWidth(0.5);
        doc.line(marginLeft, yPosition, marginRight, yPosition);
        yPosition += 5;
        break;
    }
  }

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.muted);

    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );

    doc.text(
      'Generated by UPSC PrepX-AI',
      marginLeft,
      pageHeight - 10
    );
  }

  return doc.output('blob');
}

/**
 * Generate PDF from simple text
 */
export async function generateSimplePDF(
  title: string,
  content: string,
  options: Partial<PDFOptions> = {}
): Promise<Blob> {
  const blocks: ContentBlock[] = [
    { type: 'heading', content: title, level: 1 },
    { type: 'divider', content: '' },
    { type: 'paragraph', content: content },
  ];

  return generatePDF(blocks, { ...options, title });
}

/**
 * Generate notes PDF with structure
 */
export async function generateNotesPDF(
  topic: string,
  notes: {
    introduction?: string;
    mainPoints?: string[];
    explanation?: string;
    examples?: string[];
    summary?: string[];
  },
  options: Partial<PDFOptions> = {}
): Promise<Blob> {
  const blocks: ContentBlock[] = [
    { type: 'heading', content: topic, level: 1 },
    { type: 'divider', content: '' },
  ];

  if (notes.introduction) {
    blocks.push({ type: 'heading', content: 'Introduction', level: 2 });
    blocks.push({ type: 'paragraph', content: notes.introduction });
  }

  if (notes.mainPoints && notes.mainPoints.length > 0) {
    blocks.push({ type: 'heading', content: 'Main Points', level: 2 });
    blocks.push({ type: 'list', content: notes.mainPoints });
  }

  if (notes.explanation) {
    blocks.push({ type: 'heading', content: 'Explanation', level: 2 });
    blocks.push({ type: 'paragraph', content: notes.explanation });
  }

  if (notes.examples && notes.examples.length > 0) {
    blocks.push({ type: 'heading', content: 'Examples', level: 2 });
    blocks.push({ type: 'list', content: notes.examples });
  }

  if (notes.summary && notes.summary.length > 0) {
    blocks.push({ type: 'heading', content: 'Summary', level: 2 });
    blocks.push({ type: 'list', content: notes.summary });
  }

  return generatePDF(blocks, { ...options, title: topic });
}

/**
 * Generate essay PDF
 */
export async function generateEssayPDF(
  title: string,
  essay: {
    introduction: string;
    body: string[];
    conclusion: string;
  },
  options: Partial<PDFOptions> = {}
): Promise<Blob> {
  const blocks: ContentBlock[] = [
    { type: 'heading', content: title, level: 1 },
    { type: 'divider', content: '' },
    { type: 'heading', content: 'Introduction', level: 2 },
    { type: 'paragraph', content: essay.introduction },
  ];

  for (let i = 0; i < essay.body.length; i++) {
    blocks.push({ type: 'heading', content: `Point ${i + 1}`, level: 2 });
    blocks.push({ type: 'paragraph', content: essay.body[i] });
  }

  blocks.push({ type: 'heading', content: 'Conclusion', level: 2 });
  blocks.push({ type: 'paragraph', content: essay.conclusion });

  return generatePDF(blocks, { ...options, title });
}

/**
 * Download PDF
 */
export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Get PDF as base64
 */
export function getPDFBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
